# Generated by Django 5.1.2 on 2024-10-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_statuslookup_remove_project_acceptance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslookup',
            name='status_label',
            field=models.CharField(max_length=25),
        ),
    ]
