# Generated by Django 5.1.2 on 2024-10-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_confirmed_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.IntegerField(unique=True)),
                ('currency_label', models.CharField(max_length=25)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='projectbudget',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budgets', to='projects.currencylookup'),
        ),
    ]
