# Generated by Django 5.1.2 on 2024-12-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectbudget_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslookup',
            name='status_label',
            field=models.CharField(choices=[('started', 'Open'), ('finished', 'Closed'), ('planned', 'Planned')], max_length=25),
        ),
    ]
