# Generated by Django 5.1.2 on 2024-12-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.IntegerField(unique=True)),
                ('currency_label', models.CharField(max_length=25)),
                ('exchange_rate_LC', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StatusLookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.IntegerField(unique=True)),
                ('status_label', models.CharField(choices=[('started', 'Open'), ('finished', 'Closed'), ('planned', 'Planned')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=25)),
                ('project_number', models.CharField(max_length=10, unique=True)),
                ('DATECREATE', models.DateTimeField(auto_now_add=True)),
                ('project_lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('confirmed_project_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_projects', related_query_name='status', to='api.statuslookup')),
                ('project_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_status_projects', to='api.statuslookup')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_budgets', to='api.currencylookup')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('order_date', models.DateField()),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='api.project')),
            ],
        ),
    ]
