# Generated by Django 5.1.2 on 2024-12-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_statuslookup_status_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeline',
            name='finish_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='projecttimeline',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
