# Generated by Django 5.1.2 on 2024-12-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_projecttimeline_finish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectbudget',
            old_name='budget',
            new_name='amount',
        ),
    ]
