# Generated by Django 5.1.2 on 2024-10-22 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_statuslookup_status_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='confirmed_status',
        ),
        migrations.AddField(
            model_name='project',
            name='confirmed_project_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_status_projects', related_query_name='status', to='projects.statuslookup'),
        ),
    ]
