# Generated by Django 5.1.2 on 2024-12-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_budget_projectbudget_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencylookup',
            name='exchange_rate_LC',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='projectbudget',
            name='amount',
            field=models.FloatField(blank=True),
        ),
    ]
