# Generated by Django 5.1.4 on 2025-01-06 12:54

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_currencylookup_exchange_rate_lc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="currencylookup",
            name="currency_id",
        ),
        migrations.RemoveField(
            model_name="statuslookup",
            name="status_id",
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="project_files/",
                        validators=[api.models.validate_file_extension],
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("DATECREATE", models.DateTimeField(auto_now_add=True)),
                (
                    "project_number",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file",
                        to="api.project",
                    ),
                ),
            ],
        ),
    ]
