# Generated by Django 5.1.2 on 2024-10-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_currencylookup_projectbudget_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencylookup',
            old_name='exchange_rate',
            new_name='exchange_rate_LC',
        ),
    ]
