# Generated by Django 5.1.4 on 2025-01-08 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_currencylookup_currency_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencylookup',
            old_name='exchange_rate_LC',
            new_name='exchange_rate',
        ),
    ]
