# Generated by Django 5.1.4 on 2025-01-09 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_exchange_rate_lc_currencylookup_exchange_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="confirmed_project_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_status_projects",
                related_query_name="status",
                to="api.statuslookup",
            ),
        ),
    ]
