# Generated by Django 5.1.4 on 2025-01-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_confirmed_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectfile',
            name='project_number',
        ),
        migrations.AddField(
            model_name='projectfile',
            name='project',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='api.project'),
            preserve_default=False,
        ),
    ]
