# Generated by Django 5.1.4 on 2025-04-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_projectfile_project_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KanbanOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kanban_order', to='api.project')),
            ],
        ),
    ]
